### ISSUE TITLE
Create element name generator microservice

### ISSUE THREAD

**Issue by aowie1** [observable-universe/miner#12]
To be named Elementifier

**Comment by aowie1** [comment]
I created a concept of this which turned out well. I am now working on a commit that is more refined and less buggy which should be more readable and churn out some more consistent, well-oriented and unique names.

**Comment by aowie1** [comment]
Updated this class to properly use exceptions during validations and static variables. This is a single file service currently and spits out 10 randomly generated names per real Element in an array. Just run elementifier/index.php to execute

**Comment by rreynier** [comment]
Lookin good!  

I do ask, to get us all in a good team rhythm, we should create branches and PR's for everything going back in master.  It's much easier to give feedback and understand what is happening. 

Basically, if you start working on a card/task, create a branch and go from there!

**Comment by aowie1** [comment]
I agree with this. Will do in the future.
